X-lab2017/open-digger

sqls/total-developer-count/post-processor.js
sqls/total-record-count/post-processor.js
sqls/total-repo-count/post-processor.js

In the original version, all numbers of developers and repos are pure number format which is really hard to read, so I change the output format to add comma for every 3 digits so it gonna be better for reading. Like 1234567 -> 1,234,567.

[Refactor] Change number to thousand format.

---

.github/hypertrons-components/sql_label/index.lua
.github/hypertrons.json

Close #34 , I implement the `pr_uml_renderer` component in Hypertrons because I think it could be a very common ability. See https://github.com/X-lab2017/github-analysis-report-2020/pull/33#issuecomment-679890618 for what this component can do.
Others:
- Add `auto_update_contribution` component in config
- For `pull/sql` label, only need to check `created` and `synchronize` actions for `PullRequestEvent`, no need for all kinds of actions.

[Feature] Add pr uml render component

---

.github/hypertrons-components/auto_update_contribution/index.lua

When generate contribution doc, if `score` is equal then sort by `login` so it should be a stable sort.
Close #58

[Refactor] Contribution sort alphabetically if score is equal

---

docs/architecture.md
docs/workflow.md
docs/zh-cn/architecture.md
docs/zh-cn/workflow.md

First the robot is deployed on my own laptop which is not quite easy to maintain. Now the robot is on cloud and only data service runs on my laptop.
The new base URL is `http://gar2020.opensource-service.cn` so need to change all UML render base URL to make sure they works.

[Refactor] change base url

---

.github/hypertrons-components/auto_update_report/defaultConfig.ts
.github/hypertrons-components/sql_run/defaultConfig.ts
.github/hypertrons-components/sql_run/index.lua

Add `owner`, `repo`, `baseUrl` for `sql-run` and `auto-update-report` component. 
Also add default config to `runJsCode` so `post-processor` can get the params.
This PR should be merged before #89

[Refactor] Add more param to sql run

---

REPORT_TEMPLATE.md

Relate to #89 
Add simple working hour description into template.
BTW, if we want to insert an `svg` image into markdown file, need to use `embed` tag because default way to add an image will convert to `img` tag which does not support `svg` dynamic functions.

[Docs] Add working hour to report template

---

.github/hypertrons-components/auto_update_report/index.lua
REPORT_TEMPLATE.md
docs/_sidebar.md
docs/report.md
sqls/working-hour-distribution/image.svg
sqls/working-hour-distribution/post-processor.js
sqls/working-hour-distribution/sql

Few fixes about working hour, relate to #89 
- Add global config to `runJsCode` in update report
- Fix URL param error
- Add to website in English version because dynamic `svg` file can not be rendered by GitHub markdown renderer.
- Sometimes there are no records for certain `dayOfWeek` and `hour`, so need to return `dayOfWeek` and `hour` and check later for zero values.

[Fix] Fix few things about working hour

---

README.md

Maybe someone can fix [data docs 404](https://www.x-lab.info/github-analysis-report/#/data).  But for now we can temporarily link to markdown file.
Signed-off-by: liwen-tj <liwen00812@qq.com>

fix data docs link error

---

.github/workflows/pr_test.yml
.github/workflows/publish.yml

The first version of `pr-test` action is triggered by `pull_request` event, but due to GitHub Actions rule, the event is triggered by a third party user can not get secrets in the repo.
So change the event to issue comment trigger and user with write access of the repo can trigger the event and run the action.

[Refactor] Change pull test workflow into issue comment trigger

---

.github/workflows/pr_test.yml

The event name should be `issue_comment`

[Fix] fix issue comment event name

---

global-study/sqls/repo-language-distribution/processor.js

In last version, `repo_language` is not correct column name which will cause render error and the content will all be `undefined`. Fix the column name into `language`.

[Fix] language distribution column name fix

---

src/case-study.ts
src/global-study.ts
src/index.ts

Support unit test for single or specific case studies in command line.
- If you want to run all tests, you can run `npm run test`.
- If you want to generate only global report, you can run `npm run test global`.
- If you want to generate specific case study reports, you can add all case study names as params which are case insensitive like `npm run test vscode asf`, so the test will generate test reports for `ASF.yaml` and `vscode.yaml`.
close #568

[Feature] Support unit test for single case study

---

.github/workflows/pr_test.yml
.github/workflows/publish.yml
package.json

In last workflow we use test data set for CI test on PR which will cause empty result for repos, so we need to update data set to online full data set to get the real result.

[CI] Use online data set as CI data set

---

.github/workflows/parse_github_id.yml

close #682 
Add a new GitHub Actions workflow to parse issue body and fetch repo/org/user's GitHub id automatically.
- The work should be triggered by command `/parse-github-id`.
- It will parse the issue body line by line and get the lines start with `- ` which is a list item in Markdown.
- It will fetch repo/org/user id by GitHub Rest API and reform the issue comment by original body, replace the name by id and add a yaml style comment with the type and name.
An example can be found [here](https://github.com/frank-zsy/open-digger/issues/4).

[Feature] Fetch repo and org id for issues

---

labeled_data/regions/China.yml
src/cron/tasks/hacking_force_month.ts
src/cron/tasks/hypercrx_actor.ts
src/cron/tasks/hypercrx_repo.ts
src/cron/tasks/open_leaderboard.ts
src/metrics/activity_openrank.ts
src/metrics/basic.ts
src/utils.ts

Add a cron task for open leaderboard and as well as some minor fix:
- Add Ant Group and Fit2Cloud into Chinese label.
- Change `forEveryMonth` to support async function.
- Add clickhouse version activity query.
- Change `season` to `quarter`.

[Feat] Add open leaderboard tasks

---

src/cron/tasks/hypercrx_actor.ts
src/cron/tasks/hypercrx_repo.ts
src/cron/tasks/open_leaderboard.ts

Change the time span of Hypercrx task.
The task will upload all actors and repos information about activity and influence which have at least 10 activity score in the past 6 months. This is trade-off between all active users/repos and make sure the cost is affordable.

refactor: change hypercrx time span

---

.github/hypertrons-components/auto_update_contribution/defaultConfig.ts

Fix Hypertrons config for update contribution since we do not have `sql-reviewer` role any more and change the update time to 12 o'clock every Monday.

fix: hypertrons update contribution config

---

package.json

Add `--rm` to notebook docker start command to avoid left container info after notebook stop.

chore: add --rm to notebook

---

docs/DATA.md

Fix English version doc for data description page error and `csv` file link error.

fix: fix data description in English version doc

---

package.json

Add a new npm script `notebook:win` which can be used to start notebook container under windows cmd.

feat: add windows notebook script

---

labeled_data/communities/xlab/index.yml

According to the issue comment https://github.com/X-lab2017/open-digger/issues/864#issuecomment-1171267350 , I want to add my id as X-lab members labeled data into OpenDigger.
**But my account name has been changed so my `actor_login` can also be '1054096100'. 
Should I mention it in the code comments?**
```sql
SELECT actor_login, COUNT() as name_sum
FROM github_log.events where actor_id='29705275'
GROUP BY actor_login
[Out]
actor_login  name_sum
0  1054096100       851
1   yoyo-wu98        21
```
So both `actor_login` have its own events.
Sorry if it makes something difficult:(

[Data] Add my id as X-lab members labeled data into OpenDigger

---

sample_data/README.md
sample_data/start_server.sh

According to the discussion in issue #917 , an example command line in sample_data/README.md should be corrected to avoid a bug.
As @frank-zsy mentioned in https://github.com/X-lab2017/open-digger/issues/917#issuecomment-1190953277 :
> I think we can use $(pwd) before the folder name to complete the path, which will lead another thing that under windows, this should be replaced by %cd%. This will give the command an absolute path of the folder.
So, the changes in this PR are:
1 .We correct the command line and add a notice right after it.
2. To make the guide more easy to follow, I change some context order of the doc to make the instructions sequential.

[Doc] Correct an example command line and change some context order of the sample_data/README

---

src/label_data_utils.ts

close #941 
Fix path problem under windows env as we use os separator to construct the label identifier.
So process all identifiers to linux favor path to avoid bug under windows env.

fix: fix path problem under windows env

---

src/metrics/activity_openrank.ts

Fix label group slice array bug in openrank.
`array.slice(0, -1)` will remove the last element of the array, so if limit is -1, need to use `undefined` to replace the number.

fix: fix openrank label slice

---

sample_data/README.md

Since the [Docker Hub](https://hub.docker.com/) does not have the image `open-digger-clickhouse-base` but the image `docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base`, so we cannot shorten the image name. So we have to use the full name `docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base`.

fix: Update README.md to fix a bug about the docker image name

---

sample_data/README.md

Since we have added the Python Kernel of the open-digger and there is an issue #968 asking for it, the guide of the Sample Data Usage with Python Kernel should be added.

[Doc] Add python kernel sample data guide.

---

.github/workflows/reply-label-issue-comment.yml

fix #1020 
In order to test, I created my own open-digger repo with the updated file. I used an id of other user replacing open-digger-bot's id to fliter. The flitered user' comment was not tagged and other users' comments could be tagged.

Filter opendigger-bot's comment

---

labeled_data/technology/big_data/analysis_engine.yml
labeled_data/technology/big_data/data_development.yml
labeled_data/technology/big_data/data_integration.yml
labeled_data/technology/big_data/data_storage.yml
labeled_data/technology/big_data/index.yml
labeled_data/technology/big_data/others.yml
labeled_data/technology/big_data/scheduler.yml
labeled_data/technology/big_data/streaming.yml
labeled_data/technology/big_data/visualization.yml
src/label_data_utils.ts

close #1051 
Add `Big Data` related label data, and add `Tech-0` and `Tech-1` as top level and 2nd level technology label type.
I verify the result in my local environment and I will upload several screenshots about the result.
Big data overall label repos count and overall OpenRank trending by year.
Sub area OpenRank trending by year, only change `groupBy` to `Tech-1` which means group data by 2nd level label.
Repo OpenRank trending in sub area, just use `:technology/big_data/data_storage` to access the 2nd level label.
So all works fine now on my side.

data: add big data label data

---

README.md

related to #1030 
Add a metrics or indices usage section at top of README, I think OpenDigger is more a user community than a developer community, so add the section before other parts.

doc: add metrics usage to readme.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/multivalue.yml
labeled_data/technology/database/native_xml.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/rdf.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/search_engine.yml
labeled_data/technology/database/spatial.yml
labeled_data/technology/database/time_series.yml
labeled_data/technology/database/wide_column.yml

Fix #1093
data: update database label data (total 206) refer to DB-Engines in Dec, 2022. Filter conditions:  `Rankings in the DB-Engines Rankings table in Dec, 2022` and `has open source license` and `has repository on GitHub`.

data: update database label data (total 206) refer to DB-Engines in Dec, 2022.

---

src/cron/tasks/network_export.ts

related to #1081 
Use `activity` to replace node size of developer and repo in repos' developer networks and developers' repo networks.

refactor: modify node size of networks

---

package-lock.json
package.json
src/cron/tasks/remove_rename.ts

close #1109 
Add a new cron task to remove legacy orgs and repos data from OSS.
Find all the legacy org and repo names and remove from OSS one by one to avoid leaving old data behind.
The task should run right before metrics and network data upload.

feat: cron task for removing rename legacy orgs and repos

---

labeled_data/technology/database/key_value.yml

Fix https://github.com/X-lab2017/open-digger/issues/1136
data: Update dbms labeled data incrementally based on DB-Engines in Jan, 2023. Filter conditions: `Rankings in the DB-Engines Rankings table in Jan, 2023` and `has repository on GitHub` and `not labled yet`.

data: Update dbms labeled data incrementally based on DB-Engines in Jan, 2023.

---

src/metrics/basic.ts
src/metrics/chaoss.ts
test/metrics.test.ts

close #1142 
Add a `TimeDurationOption` for all the time range metrics, they should all return `avg` for average, `levels` for thresholds levels and `quantile_0` to `quantile_4` which is the quantiles of the metrics. And the metrics should support order by any above field.
Also add a `noTotal` option to metrics test, since for time duration metrics, we use `NaN` for time range which has no data rather than 0, so `sum` will return `null` for the metrics which can not be compared.

feat: add new standard to time range metrics

---

src/metrics/chaoss.ts
src/metrics/index.ts
src/open_digger.js
test/metrics.test.ts

close #575 
Add a `chaossChangeRequestResolutionDuration` metric, which uses the same logic with `chaossIssueResolutionDuration` metric.

metric: add change request resolution duration

---

.mocharc.json
src/metrics/chaoss.ts
src/metrics/index.ts
src/open_digger.js
test/metrics.test.ts

close #574 
Add `chaossChangeRequestResponseTime` metric which reuses the logic of `chaossIssueResponseTime` metric.
Add timeout of unit test to 30s to make sure the test finishes.

metric: add change request response time

---

src/metrics/basic.ts
src/metrics/chaoss.ts
src/metrics/index.ts
src/metrics/indices.ts
src/metrics/metrics.ts
src/open_digger.js
test/metrics.test.ts

close #588 
Implement the `issue age` and `change request age` metrics.
This metric is quite tricky, right now, I do not group the metric by time range and just give the issue age metric until `endTime`.
And maybe we should have more complex and flexible unit test functions.

metric: add chaoss issue age

---

src/metrics/basic.ts
src/metrics/chaoss.ts
src/metrics/index.ts
src/open_digger.js
test/metrics.test.ts

close #591 
Inactive contributors is a very hard metric to implement, the basic logic is:
- Find out all the contributors before `endTime` for required repos and orgs.
- To each contributor, we need to get the first contribution time point and the contributions in each time range by the config, like every month or every quarter.
- Calculate the inactive contributors if the developer was contributor by end of the time range and the contributions count is smaller than the given param.
- Group all the result into arrays.
It is different from other metric that `time` column is not a group column by original data but a new column we put into just like `issue age` metric.

metric: add chaoss inactive contributor

---

src/metrics/index.ts
src/metrics/metrics.ts
src/open_digger.js
test/metrics.test.ts

close #878
In this PR, I implement a metric called `contributor email suffixes` which returns the contributors email suffix statistical results by commit email and author.
The result is always sorted by suffix count and there is no other sort or limit function for this metric since it is not quite reasonable to sort or limit the result. That's why the test is quite simple which just makes sure that the metric returns data.

metric: add contributor email suffix

---

src/cron/tasks/monthly_export.ts
src/metrics/chaoss.ts
src/metrics/index.ts
src/metrics/indices.ts
src/open_digger.js
test/metrics.test.ts

close #1160 
This PR add more metrics into monthly export task, and also fixes some bugs in metrics implementation, includes:
- Change `chaossIssuesActive` to `chaossIssuesAndChangeRequestActive` metric, since we can not easily distinguish issues and PRs in events log when type is `IssueCommentEvent`.
- Change all default value for time duration levels to `[]` rather than filling with 0 elements.
- Change age related metrics have bugs before, fix the bug and verified by OpenDigger data.

feat: export more metrics to OSS

---

src/cron/tasks/monthly_export.ts

close #1168 
When exporting data to OSS, create an empty data file for repo and user as a flag file for downstream communities.

refactor: add export flag file

---

src/metrics/basic.ts

Fix a bug when group time range is not set in query option.
Changes:
- Use `dateAdd(month, 1, toDate('${config.endYear}-${config.endMonth}-1')) AS time` if group time range is not set, because in some cases, we will use time to compare and aggregate data, so use the next month of end time will return correct result wile `1` is not right here.
- Use `created_at` rather than `time` to find out the latest names for actor and repo, because if group time range is not set, time is a constant so `argMax` will not work.

fix: fix bug for no group time range

---

src/metrics/chaoss.ts

fix #1172 
Add `reopened` action to `issuesNew` metric.
With `reopened` action involved, the total number of issues looks good, minor difference due to log data loss.

refactor: add reopened action to issues new metric

---

src/cron/tasks/monthly_export.ts

fix #1168 
Using `meta.json` as flag file instead of `owner/name.json` since the problem described in #1168

fix: use meta.json instead of name.json as flag file

---

src/cron/tasks/monthly_export.ts
src/metrics/indices.ts
test/metrics.test.ts

fix #1186 
Add a `developerDetail` option to activity index.
- With the option set to `true`, will return details about developer activity in every month.
- For monthly export task, add `activity_details.json` file to store the details of activity in every month.
- Add the option to unit test to make sure it won't break the function.

feat: add activity developer details option

---

docs/_sidebar.md
docs/data.md
docs/index.html
docs/metrics/global_openrank.md
docs/zh-cn/_sidebar.md
docs/zh-cn/data.md
docs/zh-cn/metrics/global_openrank.md
docs/zh-cn/metrics/project_openrank.md

Related to #1183 
- Add OpenRank and project OpenRank zh-cn doc in website.
- Also change `OpenRank` to `Global OpenRank` to distinguish it from `Project OpenRank`.
- Fix `Clickhouse` to `ClickHouse`.

doc(website): add zh doc for openrank

---

src/cron/tasks/monthly_export.ts

close #1186 
Slice activity detail array if the length is larger than 100 to avoid too large file like vscode.

refactor: slice activity detail in case large size file

---

labeled_data/technology/database/array.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/multivalue.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/wide_column.yml

Fix https://github.com/X-lab2017/open-digger/issues/1253
Batch label data: Incrementally add labels in April to the database technology repository.
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by Apr 13th, 2023. 
- Collected by dbdb.io on Apr 13th, 2023 OR Rankings in the DB-Engines Rankings table on Apr 13th, 2023; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1245 on Mar 31st, 2023.

Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by Apr 13th, 2023.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/key_value.yml
src/cron/tasks/monthly_export.ts
src/cron/tasks/open_leaderboard.ts

As #1267 merged, label `:regions/China` changes to `:regions/CN`, so we need to change the label in monthly export task, as well as two missing repos in database label data.

fix: change China to CN and remove 2 missing repos

---

labeled_data/technology/database/array.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/time_series.yml
labeled_data/technology/database/wide_column.yml

Fix https://github.com/X-lab2017/open-digger/issues/1283
Batch label data: Incrementally add labels in 202305 to the database technology repository.
- Collected by dbdb.io on May 7th, 2023 OR Rankings in the DB-Engines Rankings table on May 7th, 2023;
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1253 on Apr 13th, 2023.

Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by May 7th, 2023. 

---

docs/assets/data_description.csv

Add more columns in ClickHouse database.
close #1216 : Add `pull_base_ref` for the branch in the upstream repo, `pull_head_ref` as well as `pull_head_repo_id` and `pull_head_repo_name`.
close #1268 : Add `commit_comment_sha` for the SHA of the commit where the comment added.
The data has already been updated in the production ClickHouse instance.

refactor: add more columns in ClickHouse database

---

src/cron/tasks/monthly_export.ts
src/metrics/indices.ts

close #1342 
Add `repoDetail` option to user activity metrics interface and export in monthly export task too.
Also slice repoDetail and userDetail to at most 100 items in case too many data involved.

feat: add detail for user activity

---

labeled_data/technology/database/array.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1351
Batch label data: Incrementally add labels in 202307 to the database technology repository.
- Collected by dbdb.io on July 24th, 2023 OR Rankings in the DB-Engines Rankings table on July 24th, 2023;
- The increment relative to the version #1313 on June 10th, 2023.
Features:
- Add new repositories with labels in [Array, Document, Graph, Key-value, Object oriented, Relational].

Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by July 24th, 2023.

---

src/cron/tasks/monthly_export.ts

close #1357 
Export top level label data to OSS as well to support downstream applications.

feat: export label meta data

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1376
Batch label data: Incrementally add labels in 202308 to the database technology repository.
- Collected by dbdb.io on Aug 26, 2023 OR Rankings in the DB-Engines Rankings table on Aug 26, 2023;
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1351 on July 24th, 2023.
Features:
- Add new repositories with labels in [Document, Graph, Relational].

Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by Aug 26, 2023.

---

labeled_data/technology/database/array.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/vector.yml

Fix https://github.com/X-lab2017/open-digger/issues/1393
Batch label data: Incrementally add labels in 202309 to the database technology repository.
- Collected by dbdb.io on Sep 26, 2023 OR Rankings in the DB-Engines Rankings table on Sep 26, 2023;
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1376 on Aug 26, 2023.
Features:
- Add new repositories with labels in [Array, Document, Object Oriented, Relational, Vector].
Notes: 
- Last month, [dbdb.io](https://dbdb.io/) divided the label “Array / Matrix / Vector” into the label “Array / Matrix” and the label “Vector”.

Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by Sep 26, 2023. 

---

src/cron/tasks/monthly_export.ts
src/metrics/basic.ts
test/basic.test.ts

close #1105 
close #1388 
- Export quarter and year data to OSS in monthly export task.
- The new keys will be directly added into the data.
- Add basic functions `forEveryQuarterbyConfig` and `forEveryYearByConfig` as well as their unit tests.

feat: export quarter and year data to OSS in monthly export

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/time_series.yml

Fix https://github.com/X-lab2017/open-digger/issues/1416
Batch label data: Incrementally add labels in **202310** to the database technology repository.
- Collected by dbdb.io on **Oct 27, 2023** OR Rankings in the DB-Engines Rankings table on **Oct 27, 2023**;
- The **increment** relative to the version https://github.com/X-lab2017/open-digger/issues/1393 on **Sep 26, 2023**.
Features:
- Add new repositories with labels in [Document, Key-value, Object Oriented, Relational, Time Series].
Notes: 
- Last month, [AILab-FOI/akdb](https://github.com/AILab-FOI/akdb) was archived, then transferred to [minovakovi/akdb](https://github.com/minovakovi/akdb).

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking by Oct 27, 2023.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1433
Batch label data: Incrementally add labels in **202311** to the database technology repository.
- Collected by dbdb.io on **Nov 29, 2023** OR Rankings in the DB-Engines Rankings table on **Nov 29, 2023**;
- The **increment** relative to the version https://github.com/X-lab2017/open-digger/issues/1416 on **Oct 27, 2023**.
Features:
- Add new repositories with labels in [Document, Relational].
Notes: 
-  Add reason: 1 multi-labeled; 3 newly added.

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking by Nov 29, 2023.

---

labeled_data/technology/database/array.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/multivalue.yml
labeled_data/technology/database/network.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/rdf.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/spatial.yml
labeled_data/technology/database/time_series.yml

Fix https://github.com/X-lab2017/open-digger/issues/1457
Batch label data: Incrementally add labels in **202312** to the database technology repository.
- Collected by dbdb.io on **Dec 30, 2023** OR Rankings in the DB-Engines Rankings table on **Dec 30, 2023**;
- The **increment** relative to the version https://github.com/X-lab2017/open-digger/issues/1433 on **Nov 29, 2023**.
Features:
- Add new repositories with labels in [Array, Document, Graph, Key-value, Multivalue, Network, Object Oriented, RDF, Relational, Spatial, Time Series].
Notes: 
-  Add or update reasons: newly added and find some similar dbms repositories with greater influence.

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking by Dec 30, 2023.

---

src/cron/tasks/monthly_export.ts
src/cron/tasks/open_leaderboard.ts

Fix 2 minor bugs in cron task:
- Task `open_leaderboard`, end year and month configuration is not correct, will encounter error on a new year.
- Task `monthly_export`, while exporting user info, injected platform in SQL should be cast to Enum type explicitly.

fix: fix 2 bugs in cron task

---

labeled_data/companies/antgroup/sofastack.yml

Fix platform name error for Sofastack label.

fix: fix platform error in sofastack

---

labeled_data/companies/baidu/doris.yml
labeled_data/companies/baidu/index.yml

Add `doris` as a single project label and add it into `baidu` label.

label: add doris to baidu

---

labeled_data/companies/baidu/echarts.yml
src/label_data_utils.ts

Add `parents` and `children` identifiers in label data which makes the labels have hierarchy levels.
Fix echarts label name.

feat: add parents and children in label

---

labeled_data/technology/ai/generative_ai/application/audio.yml
labeled_data/technology/ai/generative_ai/application/code.yml
labeled_data/technology/ai/generative_ai/application/image.yml
labeled_data/technology/ai/generative_ai/application/index.yml
labeled_data/technology/ai/generative_ai/application/other.yml
labeled_data/technology/ai/generative_ai/application/text.yml
labeled_data/technology/ai/generative_ai/application/video.yml
labeled_data/technology/ai/generative_ai/index.yml
labeled_data/technology/ai/generative_ai/infrastructure/data.yml
labeled_data/technology/ai/generative_ai/infrastructure/document.yml
labeled_data/technology/ai/generative_ai/infrastructure/index.yml
labeled_data/technology/ai/generative_ai/infrastructure/platform_and_environment.yml
labeled_data/technology/ai/generative_ai/infrastructure/vector_database.yml
labeled_data/technology/ai/generative_ai/model/framework_and_architecture.yml
labeled_data/technology/ai/generative_ai/model/fundamental_model.yml
labeled_data/technology/ai/generative_ai/model/index.yml
labeled_data/technology/ai/generative_ai/model/variant_model.yml
labeled_data/technology/ai/generative_ai/tool/deployment_tool.yml
labeled_data/technology/ai/generative_ai/tool/develop_tool.yml
labeled_data/technology/ai/generative_ai/tool/index.yml
labeled_data/technology/ai/generative_ai/tool/production_monitor.yml
labeled_data/technology/ai/generative_ai/tool/prompt_engineering.yml
labeled_data/technology/ai/large_language_model/index.yml
labeled_data/technology/cloud_native/app_definition_and_development/application_definition_and_image_build.yml
labeled_data/technology/cloud_native/app_definition_and_development/continuous_integration_and_delivery.yml
labeled_data/technology/cloud_native/platform/certified_kubernetes_distribution.yml
labeled_data/technology/cloud_native/platform/certified_kubernetes_hosted.yml
labeled_data/technology/cloud_native/platform/certified_kubernetes_installer.yml
src/label_data_utils.ts

Fix https://github.com/X-lab2017/open-digger/issues/1484
- Fix miss counting bug: Add the untracked categories into its parent node index.yml label list.
- Fix mixed counting bug: Change the 'Tech-N' label to match the default template: increase N from root node to leaf node based on depth.
Notes: *.yml files mentioned below do not including index.yml.
- Fix miss counting bug in [:technology](https://github.com/X-lab2017/open-digger/tree/master/labeled_data/technology)`: 
- Add missing index.yml: `:technology/ai/generative_ai/infrastructure/index.yml .
- Add 3rd depth `:technology/ai/generative_ai/infrastructure/*.yml` into `:technology/ai/generative_ai/infrastructure/index.yml` label list; 
- Add 3rd depth `:technology/ai/generative_ai/application/*.yml` into …

Fix Bug: Correct labels of yaml files in labeled_data directory.

---

src/metrics/index.ts
src/metrics/indices.ts
src/open_digger.js

Related to #1497 
Add a community OpenRank interface for OpenDigger, but not added into export task yet.

feat: add community openrank metric interface

---

src/metrics/basic.ts
src/open_digger.js
src/utils.ts

Refactor some minor places:
- Remove `openDigger.quick` API which is deprecated.
- Refactor `getLogger` function, make sure the time printed is for current timezone now but not UTC.
- Fix `getMergedConfig` with `endYear` and `endMonth` default value which is not correct for Jan. right now.

refactor: some minor refactors

---

labeled_data/technology/database/key_value.yml
labeled_data/technology/database/vector.yml

Fix https://github.com/X-lab2017/open-digger/issues/1517
Batch label data: Incrementally add labels in April to the database technology repository.
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by Jan 28, 2024. 
- Collected by dbdb.io on Jan 28, 2024 OR Rankings in the DB-Engines Rankings table on Jan 28, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1457 on Dec 30, 2023.
Features:
- Add 1 repo "oasysai/oasysdb" with multi-labels: ["Key-value", "Vector"].

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking by Jan 28, 2024.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1528
Batch label data: Incrementally add labels in April to the database technology repository.
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by Feb 29, 2024. 
- Collected by dbdb.io on Feb 29, 2024 OR Rankings in the DB-Engines Rankings table on Feb 29, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1517 on Jan 28, 2024.
Features:
- Add 3 repositories with labels in ["Relational", "Document"].
- Delete 1 repository "CeresDB/ceresdb" for the datebase CeresDB can no longer be retrieved by [dbdb.io](https://www.dbdb.io/).

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking by Feb 29, 2024.

---

src/metrics/chaoss.ts
src/metrics/indices.ts

fix #1540 
For all the metrics that has a inner query block in `getGroupIdClause`, we should use `max(created_at)` as the column to determine the `name` column rather than use `month` or other aggregated column.

fix: fix wrong name for change name repos.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1543
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to Mar 31, 2024. 
- Collected by dbdb.io on Mar 31, 2024 OR Rankings in the DB-Engines Rankings table on Mar 31, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1528 on Feb 29, 2024.
Features:
- Add 4 new repositories with labels in ["Relational", "Document", "Key-value"].
- Update 1 repository github link to "LonaDB/Server".

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to Mar 31, 2024.

---

labeled_data/technology/database/array.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/time_series.yml
labeled_data/technology/database/vector.yml

Fix https://github.com/X-lab2017/open-digger/issues/1551
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to Apr 30, 2024. 
- Collected by dbdb.io on Apr 30, 2024 OR Rankings in the DB-Engines Rankings table on Apr 30, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1543 on Mar 31, 2024.
Features:
- Add 12 new repositories with labels in ["Array", "Document", "Graph", "Key-value", "Object Oriented", "Relational", "Time Series", "Vector"].

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to Apr 30, 2024.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/time_series.yml
labeled_data/technology/database/vector.yml

Fix https://github.com/X-lab2017/open-digger/issues/1573
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to May 30, 2024. 
- Collected by dbdb.io on May 30, 2024 OR Rankings in the DB-Engines Rankings table on May 30, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1551 on Apr 30, 2024.
Features:
- Add 8 new repositories with labels in ["Document", "Key-value", "Object Oriented", "Relational", "Time Series", "Vector"].

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to May 30, 2024.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1582
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to June 30, 2024. 
- Collected by dbdb.io on June 30, 2024 OR Rankings in the DB-Engines Rankings table on June 30, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1573 on May 30, 2024.
Features:
- Add 7 new repositories with labels in ["Document", "Object Oriented", "Relational"].

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to June 30, 2024.

---

labeled_data/technology/database/graph.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1599
Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to July 31, 2024. 
- Collected by dbdb.io on July 31, 2024 OR Rankings in the DB-Engines Rankings table on July 31, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1583 on June 30, 2024.
Features:
- Update 1 repository name with labels in ["Graph"].
- Add 1 new repository with labels in ["Relational"].

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to July 31, 2024.

---

labeled_data/technology/database/columnar.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/index.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/search_engine.yml
labeled_data/technology/database/wide_column.yml

Fix https://github.com/X-lab2017/open-digger/issues/1610
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to August 29, 2024. 
- **Update database/index.yml**: import the new label "Columnar" from DB-Engines.
- Collected by dbdb.io on August 29, 2024 OR Rankings in the DB-Engines Rankings table on August 29, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1599 on July 31, 2024.
Features:
- Add 1 new label "Columnar" imported from DB-Engines into database/index.yml.
- Update 1 repository name with labels in …

Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to August 29, 2024 and update database/index.yml.

---

src/cron/tasks/global_openrank.ts

In this PR, I modify the global OpenRank algorithm for a little bit.
- Use `PushEvent` instead of `PullRequest` merge event, because actually the pull request merge event will lead to a corresponding push event, but direct push will not contain a pull request event. Although we would like to encourage issue and pull request collaboration, direct pushes are also widely occurs in the open source world even in many really important projects. To fit the different collaboration model in open source world, use `PushEvent` with a relatively low weight will do.
- Set the monthly activity limit for a single developer to the 75th percentile of the overall active users, which is approximately achieving 2 PRs per month to reach the limit for that month.
- Output the users who active in more 300 repos …

refactor: use PushEvent in global openrank

---

labeled_data/bot/index.yml
src/cron/tasks/open_leaderboard.ts
src/metrics/indices.ts

This PR:
- Add a few more bot account
- Use user community OpenRank instead of user global OpenRank in OpenLeaderboard.
- To accomplish the second one, add `withoutDetail` option to user community OpenRank interface to reduce the memory use.
- Still the monthly data for global user OpenRank is too memory consuming for ClickHouse database so split the query to batches and merge in local memory.

feat: change open leaderboard user list to community openrank

---

labeled_data/foundations/linux_foundation/lfai/index.yml
labeled_data/foundations/linux_foundation/lfai/milvus.yml

If a project label has more than 1 source, the project result will be wrong and contain more than 1 same item.
So fix the milvus label, the AI tech label will directly use the company's project label.

fix: fix milvus label to has a single source

---

src/metrics/basic.ts
src/metrics/indices.ts

This PR,
- Optimize the custom repo names, org names and user logins transfer to ids, only use `global_openrank` table rather than original `events` table which is much faster.
- Optimize the user community OpenRank API, filter the original data with user ids which helps a lot in memory consumption.

refactor: optimize the openrank sql

---

src/metrics/indices.ts

Add `legacy=0` for user and repo OpenRank interface.
Since `legacy=1` means the record is a legacy result, and it means that the repo or user did not really active in current month, only calculate the result by history data with attenuation.
In OpenLeaderboard and other related application, we should not really care about the inactive repos and users, so add the limitation in the interface to filter the legacy records.

refactor: add legacy limit for openrank interface.

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1631
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to October 31, 2024. 
- Collected by dbdb.io on October 31, 2024 OR Rankings in the DB-Engines Rankings table on October 31, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1610 on August 29, 2024.
Features:
- Add 5 new repositories with labels in ["Document", "Key-value", "Relational"].

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to October 31, 2024.

---

labeled_data/institutions/cug/index.yml
labeled_data/institutions/hubu/index.yml
labeled_data/institutions/hust/index.yml
labeled_data/institutions/whu/index.yml
labeled_data/regions/CN/hubei.yml
src/label_data_utils.ts

label: add hubei university label

---

labeled_data/technology/database/key_value.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1653
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to November 29, 2024. 
- Collected by dbdb.io on November 29, 2024 OR Rankings in the DB-Engines Rankings table on November 29, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1631 on October 31, 2024.
Features:
- Add 2 new repositories with labels in ["Key-value", "Relational"].

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to November 29, 2024.

---

README.md

Fix #1658 
Update the root URL of OpenDigger static data and replace the `open-digger` in the URL with `open_digger`.

Update the root URL of OpenDigger static data

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/wide_column.yml

Fix https://github.com/X-lab2017/open-digger/issues/1664
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to December 30, 2024. 
- Collected by dbdb.io on December 30, 2024 OR Rankings in the DB-Engines Rankings table on December 30, 2024; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1653 on November 29, 2024.
Features:
- Add 6 new repositories with labels in ["Document", "Relational", "Wide column"].
- 1 repo changed name: `LonaDB/Server` -> `Lona-Development/Server`
- Due to no longer being open source, 1 repo …

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to December 30, 2024.

---

labeled_data/technology/database/graph.yml
labeled_data/technology/database/key_value.yml

Fix https://github.com/X-lab2017/open-digger/issues/1676
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to January 29, 2025. 
- Collected by dbdb.io on January 29, 2025 OR Rankings in the DB-Engines Rankings table on January 29, 2025; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1664 on December 30, 2024.
Features:
- Add 2 new repositories with labels in ["Graph", "Key-value"].

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to January 29, 2025.

---

src/metrics/chaoss.ts

close #1663
The duration or response time related metrics has negative value due to time zone issue while dealing with default timestamp.
So use `toYYYYMMDD(time)=19700101` rather than accurate time comparison to avoid time zone related issues.

fix: fix duration related metrics

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1684
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to March 03, 2025. 
- Collected by dbdb.io on March 03, 2025 OR Rankings in the DB-Engines Rankings table on March 03, 2025; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1676 on January 29, 2024.
Features:
- Update 1 repository with labels in ["Object Oriented",  "Relational"]. The updated repo_name `[from, to, reason]` list: 
[["edgedb/edgedb", "geldata/gel", owner changed to [Gel Data …

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to March 03, 2025 for the February update.

---

labeled_data/technology/database/document.yml

Fix https://github.com/X-lab2017/open-digger/issues/1691
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to March 31, 2025. 
- Collected by dbdb.io on March 31, 2025 OR Rankings in the DB-Engines Rankings table on March 31, 2025; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1684 on March 03, 2024.
Features:
- Add 1 new repository with labels in ["Document"].
Notes:
- The changes overview: [issue_body_format_parse_github_id.txt](https://github.com/birdflyi/wiget_autogen_issue_body_for_opendigger_submiting_labeled …

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to March 31, 2025.

---

src/metrics/indices.ts

The repo name of OpenRank metrics are not correct for quarter or year group range, fix it by specify the time column of group time clause.

fix: fix repo name in group clause

---

labeled_data/technology/database/document.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/vector.yml

Fix https://github.com/X-lab2017/open-digger/issues/1696
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to April 30, 2025. 
- Collected by dbdb.io on April 30, 2025 OR Rankings in the DB-Engines Rankings table on April 30, 2025; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1691 on March 31, 2024.
Features:
- Add 3 new repositories with labels in ["Document", "Graph", "Vector"].
Notes:
- The repo_id is queried from `repository_url` api `https://api.github.com/repos/{owner}/{repo}`.

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to April 30, 2025.

---

labeled_data/technology/database/key_value.yml
labeled_data/technology/database/relational.yml

Fix https://github.com/X-lab2017/open-digger/issues/1709
Update Data: 
- Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines up to July 31, 2025. 
- Collected by dbdb.io on July 31, 2025 OR Rankings in the DB-Engines Rankings table on July 31, 2025; 
- The increment relative to the version https://github.com/X-lab2017/open-digger/issues/1703 on May 30, 2024.
Features:
- Add 2 new repositories with labels in ["Key-value", "Relational"].
Notes:
- The repo_id is queried from `repository_url` api `https://api.github.com/repos/{owner}/{repo}`.

label: Update data for Database technical area labled on dbdb.io and DB-Engines Ranking up to July 31, 2025.
