X-lab2017/open-digger

.github/hypertrons.json

Add hypertrons config so we can setup a bot to help maintain this project.

feat: add hypertrons config

---

.github/hypertrons-components/decorators.ts
.github/hypertrons-components/sql-verified/config.ts
.github/hypertrons-components/sql-verified/defaultConfig.ts
.github/hypertrons-components/sql-verified/index.lua
.github/hypertrons-components/sql-verified/version.json
.github/hypertrons.json

Add sql related component to test.

feat:add-sql-comp

---

README.md

add invite link of Slack into README.md

docs:add slack link

---

LICENSE-CC-BY
README.md

Close #20 Add CC-BY-4.0 license and license badges in Readme.

[Docs] Add cc by 4 license and badge

---

docs/diagrams/pull-flow.uml
docs/workflow.md
docs/zh-cn/workflow.md

Add first edition workflow doc by introducing the Hypertrons components used in this project.
Close #24

[Docs] Add workflow docs

---

.github/hypertrons.json

Add @sunshinemingo to committer.
Close #42

community: add new committer

---

README.md

Change join `Slack` link from text to a badge to better presentation.

[Docs] Change slack join link to badge

---

docs/README.md
docs/zh-cn/README.md

Add website readme which is the first page of the website.

[Docs] Add website readme

---

docs/CONTRIBUTING.md
docs/zh-cn/CONTRIBUTING.md

This PR adds contributing guide to website.
Please @frank-zsy  help review this if I miss something that need to be added. 
close #22 .
Signed-off-by: LinHaiming <lhming23@outlook.com>

docs: add contributing guide.

---

.github/hypertrons-components/sql_run/defaultConfig.ts
sqls/working-hour-distribution/image.svg
sqls/working-hour-distribution/manifest.json
sqls/working-hour-distribution/post-processor.js
sqls/working-hour-distribution/sql

Close #83 
Add working hour stats, use `svg` to implement the image

[Feature] Add working hour sql component

---

REPORT_TEMPLATE.md

Add some description about the word cloud.

[Docs]Add word cloud description

---

README.md

The previous invitation link expired, so update the link.

[Docs] Update slack url

---

REPORT_TEMPLATE.md
sqls/developers-top/manifest.json
sqls/developers-top/post-processor.js
sqls/developers-top/sql

Add top developers rank list to report, total activity, participant repo count, open issue count, issue comment count, open pull count, pull review comment count, merged pull count included.
close #205

[Feature] Add top developers rank list

---

sqls/activity-repo-top/post-processor.js
sqls/activity-repo-top/sql

Add total open issue count, open pr count, issue comment count, pr review comment count and pr merged count and active developers' count for every repo.

[Refactor] Add more details for top repos

---

sqls/activity-repo-top/post-processor.js
sqls/activity-repo-top/sql
sqls/developers-top/post-processor.js
sqls/developers-top/sql

changes for top repos and develop

---

case-study/ASF/REPORT_TEMPLATE.md
case-study/ASF/manifest.json
case-study/CNCF/REPORT_TEMPLATE.md
case-study/LFAIData/REPORT_TEMPLATE.md
case-study/Wuhan2020/REPORT_TEMPLATE.md

This pull request contains basic template markdown files of case study like ASF, CNCF, LFAI and Wuhan2020.
Developers can add text into the template file without think about the SQLs and general data analysis.
Still we need a `manifest.json` file to config the repos of the case study.
Related to #204

[Feature] Case study basic files

---

.github/hypertrons-components/auto_update_case_study/config.ts
.github/hypertrons-components/auto_update_case_study/defaultConfig.ts
.github/hypertrons-components/auto_update_case_study/index.lua
.github/hypertrons-components/auto_update_case_study/version.json
case-study/sqls/activity-repo/manifest.json
case-study/sqls/activity-repo/post-processor.js
case-study/sqls/activity-repo/sql

This is the hypertrons component for generating case study report, need to merge to test.
Relate to #204

[Feature] Case study hypertrons component

---

.github/hypertrons-components/auto_update_case_study/index.lua

refactor: lua syntax fix

---

.github/hypertrons-components/auto_update_case_study/defaultConfig.ts

refactor: component name fix

---

case-study/LFAIData/REPORT_TEMPLATE.md

add incubate procedure of LF AI projects

[Docs] add incubate procedure

---

case-study/ASF/REPORT_TEMPLATE.md

Add activity render text to ASF template.

[Refactor] Add activity to ASF

---

case-study/CNCF/REPORT_TEMPLATE.md
case-study/CNCF/manifest.json

- Add CNCF report template(English and Chinese)
- And CNCF case study manifest

[Docs] add CNCF report template and manifest

---

.github/hypertrons-components/auto_update_report/config.ts
.github/hypertrons-components/auto_update_report/defaultConfig.ts
.github/hypertrons-components/auto_update_report/index.lua

Add pre processor to SQL component which will accept manifest config as param and can return an object for render SQL.
close #265

[Feature] Add pre processor

---

docs/_sidebar.md
docs/case-study/CNCF.md
docs/case-study/LFAI.md
docs/case-study/Wuhan2020.md
docs/index.html
docs/zh-cn/_sidebar.md
docs/zh-cn/case-study/CNCF.md
docs/zh-cn/case-study/LFAI.md
docs/zh-cn/case-study/Wuhan2020.md

- Add case study report into website.
- Move report to top level.

[Docs] Add case study to website

---

case-study/ASF/REPORT_TEMPLATE.md
case-study/ASF/manifest.json

- Add ASF report template
- And ASF case study manifest
Signed-off-by: LinHaiming <lhming23@outlook.com>

[Docs] add ASF report template and manifest 

---

.github/hypertrons-components/auto_update_report/index.lua
sqls/activity-repo-top-Chinese/post-processor.js

Fix several things about Chinese repo SQL component.
For hypertrons `auto_update_report` component
- Need to pass self component config into post processor as the third param, the second param is the global default render params.
For Chinese SQL component:
- As returned `id` columns are in string type, need to change `org_id_company_map` and `repo_id_company_map` key to string type, otherwise will not find the correct company.
- As returned integer number columns are in string type, need to use `parseInt` to change into `int` because need to calculate later.
- the `company_info_list` is not in correct format, need to change into an array with array elements and the `activity` needs to be fixed to 2 digits as add operation will do some …

[Fix] Several changes to Chinese repo 

---

.github/hypertrons-components/auto_update_report/index.lua
REPORT_TEMPLATE.md

There are two changes:
- As Chinese SQL component will return an object(table), so log the result with text join will throw an error, so ignore the result.
- The config in Chinese template is not right.

[Fix] Few things about Chinese report

---

case-study/sqls/working-hour-distribution/post-processor.js

Fix some errors about the working hour case study component.
- Use `k` instead of `i` as loop param because `i` is used in inner loop which will cause a infinite loop here.
- Add repo name to render text to indicate which repo the image belongs to.
- Use string interpolation instead of string join with `+`.

[Fix] Working hour for case study

---

docs/_sidebar.md
docs/case-study/ASF.md
docs/zh-cn/_sidebar.md
docs/zh-cn/case-study/ASF.md

[Feature] Add ASF report to website

---

docs/case-study/ASF.md
docs/zh-cn/case-study/ASF.md

Fix report from template to report file.

[Fix] ASF report website

---

case-study/ASF/REPORT_TEMPLATE.md
case-study/CNCF/REPORT_TEMPLATE.md
case-study/LFAIData/REPORT_TEMPLATE.md

Add case study SQL render text to case study report template.

[Refactor] Add case sql result into report

---

.github/hypertrons-components/sql_run/config.ts
.github/hypertrons-components/sql_run/defaultConfig.ts
.github/hypertrons-components/sql_run/index.lua

Support pre processor logic in sql-run component so CI can return right result to PR.

[Feature] Support pre processor in ci

---

docs/CONTRIBUTING.md
docs/zh-cn/CONTRIBUTING.md

I found on the contributing guide page that some serial numbers are incorrect on the Chinese page and the English page, so I submitted this pr.

[bug]Modify the error serial number

---

sqls/activity-repo-top-Chinese/manifest.json

I correct some errors about repos. I think we should check this config. Maybe there are some actors and repos not in this.

update Chinese_repo config

---

ROADMAP.md

Add recent roadmap into the project.

[Docs] Add roadmap

---

docs/diagrams/architecture.svg

Add architecture SVG file into the docs folder.

[Docs] Add architecture svg file

---

docs/csv/data_description.csv

While we modify our architecture of the project, we also modify the data structure of the database. Includes:
- Add `pull_request_commit_sha` column which can be used to relate `PullRequestEvent` and `PushEvent`.
- Change array items from JSON string into Clickhouse `Nested` type for analysis
- `issue_labels` which contains `name`, `color`, `default`, `description`
- `issue_assignees` which contains `id`, `login`
- `push_commits` which contains `name`, `email`, `message`
- `gollum_pages` which contains `page_name`, `title`, `action`
- `release_assets` which contains `name`, `uploader_id`, `uploader_login`, `content_type`, `state`, `size`, `download_count`

[Docs] Modify data description

---

src/index.ts

fix: workflow fix

---

src/index.ts

Should use issue number rather than pull request number in event.

[Fix] Use issue number for comment

---

.github/workflows/pr_test.yml

Use issue number instead of pull request number in actions.

[Fix] use issue number

---

src/index.ts

In markdown format, we should have 2 newlines

[Fix] pull test comment should have 2 newlines

---

.github/workflows/pr_test.yml

In the old workflow, the action will checkout the master branch of upstream repository which is not correct for pull request test.

[Fix] Checkout pull ref in pull test workflow

---

.github/hypertrons.json
REPORT_TEMPLATE.html
assets/working-hour-distribution.svg
global-study/config.yaml
global-study/sqls/overview/processor.js
global-study/sqls/repo-language-distribution/processor.js
global-study/sqls/repo-language-distribution/readme.md
global-study/sqls/top-activity-developer/processor.js
global-study/sqls/top-activity-developer/readme.md
global-study/sqls/top-activity-repo/processor.js
global-study/sqls/top-activity-repo/readme.md
global-study/sqls/working-hour-distribution/processor.js
global-study/sqls/working-hour-distribution/readme.md
src/global-study.ts
src/pageUtils.ts

Migrate old global SQLs, includes: 
- Top activity repo
- Repo language distribution
- Top activity developers
- Working hour distribution
And also provide table generator for page utils.

[Feature] Migrate global sqls

---

REPORT_TEMPLATE.html
case-study/sqls/overview/processor.js
global-study/config.yaml
global-study/sqls/overview/processor.js
global-study/sqls/repo-language-distribution/processor.js
global-study/sqls/top-activity-developer/processor.js
global-study/sqls/top-activity-repo/processor.js
global-study/sqls/working-hour-distribution/processor.js
src/pageUtils.ts

Change the report style into a fashion dark one.

[Refactor] Change report style

---

REPORT_TEMPLATE.html
src/pageUtils.ts

Add `Save As PDF` button in the bottom of the page so user can download report as PDF by clicking the button.

[Feature] Add save as pdf button

---

README.md
case-study/cases/Chinese.yaml
case-study/cases/vscode.yaml
case-study/sqls/Chinese-repo-company-analysis/processor.js
case-study/sqls/issue-response-resolve-period/processor.js
src/local.ts
src/pageUtils.ts
src/utils.ts

- Add case study support and issue response and resolve period components.
- close #207 
- related to #546
- Add Chinese open source projects study report. 
- close #206 
- close #470 
- close #474 
- close #485

[Feature] Case study for issue response and resolve period & Chinese projects

---

package.json

Update test docker image to add full VSCode event log data to meet case study requirements.
close #556

[Feature] Update docker with full VSCode data

---

case-study/sqls/issue-response-resolve-period/processor.js
src/case-study.ts
src/pageUtils.ts

Add select data sql function so developer can use this function to retrieve data for certain repos and orgs without concerning the tables, it will union all data into a temp table for further use.

[Feature] Add select data sql function

---

README.md
docs/community_meeting_record.yaml

I updated slack invitation link  and community meeting record

[Docs] update_slack_link & update_meeting_record

---

.github/workflows/publish.yml

As upload oss GitHub Actions has been upgrade, need to modify the workflow file to fit the new actions config.

[Refactor] Update oss actions workflow

---

case-study/cases/Chinese.yaml

Add ossrs into Chinese list.
close #671

[Feature]Add ossrs into Chinese list

---

.github/ISSUE_TEMPLATE/ordinary_issue.md
.github/ISSUE_TEMPLATE/submit_labeled_data.md

There are two new template files users can choose.
#677

Add new issue templates for submitting labeled data and ordinary issue

---

.github/ISSUE_TEMPLATE/submit_labeled_data.md

Refactor labeled data issue template from Markdown table into Markdown list to simplify developers work to submit data.
close #677

[Refactor] Refactor labeled data template

---

labeled_data/companies/google/index.yml
labeled_data/companies/meta/index.yml
labeled_data/companies/microsoft/index.yml
labeled_data/companies/salesforce/index.yml

Add company label data for
- Google close #732 
- Microsoft close #733 
- Salesforce close #735 
- Meta close #736

[Data] Add label data for companies

---

notebook/hacking_heros.ipynb
src/config.ts
src/db/clickhouse.ts
src/db/neo4j.ts

Add a new notebook about hacking heros.

[Feature] Add hacking hero support

---

notebook/Chinese_open_source_annual_report.ipynb

Add Chinese open source report notebook.

[Notebook] Add Chinese open source report

---

labeled_data/companies/alibaba/index.yml
labeled_data/companies/alibaba/nacos.yml

Add Nacos project label data.
close #749

[Label] Add nacos label data

---

labeled_data/companies/amazon/aws_amplify.yml
labeled_data/companies/amazon/aws_cdk.yml
labeled_data/companies/amazon/aws_distro_for_opentelemetry.yml
labeled_data/companies/amazon/babelfish_for_postgresql.yml
labeled_data/companies/amazon/bottlerocket.yml
labeled_data/companies/amazon/eks_distro.yml
labeled_data/companies/amazon/firecracker.yml
labeled_data/companies/amazon/freertos.yml
labeled_data/companies/amazon/index.yml
labeled_data/companies/amazon/opensearch.yml

close #751 
Add partial AWS important project labels.

[Label] Add partial AWS data

---

labeled_data/companies/amazon/index.yml

Signed-off-by: Xiaoya <xiaoyaxiaesther@gmail.com>
close #753

Add new Amazon open source orgs

---

.github/ISSUE_TEMPLATE/submit_chinese_developer_data.md

Update issue template for Chinese user submit.

[Doc] Update issue template

---

labeled_data/companies/netflix/index.yml
labeled_data/companies/vmware/index.yml

Add Netflix and update VMWare label data

---

.gitignore
package-lock.json
package.json
src/config.ts
src/cron/index.ts
src/cron/tasks/hacking_force_month.ts
src/metrics/basic.ts
src/oss/ali.ts

Add AliOSS util interface and cron task support and add hacking force simple data as the first cron task.

[Feat] Add oss util and cron task support

---

package-lock.json
package.json
src/config.ts
src/cron/tasks/hacking_force_month.ts
src/cron/tasks/hypercrx_actor.ts
src/cron/tasks/hypercrx_repo.ts
src/db/clickhouse.ts
src/db/neo4j.ts
src/oss/ali.ts
src/utils.ts

This PR add Ali OSS client support and hypercrx task for repos and actors info.

[Feature] Add oss client and hypercrx task

---

.github/hypertrons.json

Change the role of community.
- Remove @sunshinemingo and @wengzhenjie from committer and issue replier
- Add @gymgym1212 and @xiaoya-Esther to committer and issue replier

[Community] Change role of the community

---

labeled_data/companies/emq/index.yml
labeled_data/companies/oneflow/index.yml
labeled_data/companies/taos/index.yml
labeled_data/companies/zilliz/index.yml
labeled_data/regions/China.yml
src/db/clickhouse.ts
src/db/neo4j.ts

Add EMQ, Zilliz, Taos, Oneflow label data.
close #788 close #789 close #790 close #791

label: add new company data

---

.github/workflows/check_label_pr.yml
package-lock.json
package.json
src/ci/pull_label_file_test.ts
src/ci/utils.ts
src/config.ts

Add a CI test for label data PR to generate readable content for structural YML files so reviewers can check the PR easily.
close #803

[Feature] Add CI test for label data PR

---

labeled_data/companies/qingcloud/index.yml

You can get more details about this GitHub organization from https://radondb.com/about/. There is an introduction video on that page.

Add one more org which belongs to QingCloud

---

labeled_data/companies/merico/index.yml

The name is Merico. The Chinese name is `思码逸`. See also https://www.merico.cn/our-story

Add a new company which comes from China

---

src/cron/tasks/hypercrx_actor.ts
src/cron/tasks/hypercrx_repo.ts

Remove all preceding 0 values from repos and actors in Hypercrx data.
close #811

refactor: remove 0 values from hypercrx data

---

labeled_data/regions/China.yml

Add new developer account for Chinese region.
close #817

data: add new chinese developer

---

package.json

feat: add notebook script

---

docs/zh-cn/data.md

Fix #827 Use full GitHub URL rather than relative path in doc.

fix: fix bad link in doc

---

docs/zh-cn/_sidebar.md
docs/zh-cn/events.md

[docs] Add 'events' website page to distrbute Summer 2022 participation

---

labeled_data/companies/qingcloud/index.yml

See also the following screenshots:

Add a new GitHub org which belong to QingCloud

---

README.md

fix: fix data link in readme

---

README.md

Add ClickHouse demo notebook into README

doc: add clickhouse demo notebook

---

labeled_data/companies/shanghai_ai_lab/index.yml
labeled_data/regions/China.yml

feat: add shanghai ai lab data

---

labeled_data/communities/openmmlab/index.yml
labeled_data/regions/China.yml

data: move openmmlab to community

---

.gitignore
sample_data/README.md
sample_data/build/Dockerfile
sample_data/build/Dockerfile_arm
sample_data/build/build_image.sh
sample_data/build/build_image_arm.sh
sample_data/build/initdb.sh
sample_data/export_sample.sh
sample_data/sql_files/2015_2021_top50_year.sql
sample_data/sql_files/2020_full.sql
sample_data/start_server.sh

feat: add sample data related files

---

sample_data/README.md
sample_data/build/build_image_arm.sh

fix: fix arm dockerfile and add docs.

fix: fix dockerfile and doc

---

README.md
sample_data/README.md

Update document, add sample data doc link into README.

doc: update

---

src/metrics/activity_openrank.ts
src/metrics/related_users.ts

Fix limit config in Neo4j query.
Remove activity calculation and ordering for related user query to reduce query time.

fix: fix some neo4j query

---

sample_data/README.md
sample_data/export_sample.sh
sample_data/sql_files/second_sample.sql

Add a new sample data. Second sample data extract all events with 1 second in 1 hour.

feat: add second sample data

---

sample_data/README.md

Signed-off-by: cyk <cyk_cd@163.com> I have already added a document for Jupyter Notebook image usage in README.md.

docs: Add document for Jupyter Notebook image usage (#860)

---

sample_data/README.md

close #875 
Signed-off-by: Xiaoya <xiaoyaxiaesther@gmail.com>

[document] Update sample data and notebook usage

---

labeled_data/companies/bytebase/index.yml
labeled_data/companies/guojusoft/index.yml
labeled_data/companies/koderover/index.yml
labeled_data/companies/starrocks/index.yml
labeled_data/regions/China.yml

Add new label data for companies.
close #879 
close #880 
close #881 
close #882

data: add new label data

---

.github/hypertrons.json

Signed-off-by: Xiaoya <xiaoyaxiaesther@gmail.com>

Update GitHub username

---

labeled_data/companies/rtthread/index.yml
labeled_data/regions/China.yml

label: add rtthread

---

labeled_data/communities/xlab/index.yml

[Data] X-lab member

---

src/cron/tasks/open_leaderboard.ts

Add a pre check and mkdir for open leaderboard data task.

refactor: add mkdir for leaderboard

---

sample_data/README.md
sample_data/sql_files/paddle_hackathon_3.sql

Add data for Paddle Hackathon.

data: add data for paddle hackathon

---

labeled_data/companies/alibaba/index.yml

data: add new alibaba orgs

---

labeled_data/companies/alibaba/index.yml
labeled_data/companies/alibaba/open_messaging.yml
labeled_data/companies/alibaba/weex.yml
labeled_data/companies/antgroup/index.yml

data: modify alibaba label

---

src/label_data_utils.ts
src/metrics/activity_openrank.ts
src/metrics/basic.ts

Support inject label data so users can inject their own data that not included in OpenDigger label data.

feat: support inject label data

---

src/metrics/basic.ts

close #925 
Fix a condition bug in neo4j.

fix: neo4j user condition

---

labeled_data/communities/xlab/index.yml

data: add member to x-lab

---

labeled_data/companies/bytedance/cloudwego.yml
labeled_data/companies/bytedance/index.yml
notebook/handbook.ipynb
notebook/handbook_zh.ipynb

data: add cloudwego

---

labeled_data/communities/mulan/index.yml
labeled_data/regions/China.yml

close #814 
Add Mulan community data.

data: Add mulan community

---

labeled_data/companies/antgroup/index.yml

data: add new orgs for antgroup

---

.gitignore
Dockerfile
notebook/handbook_py.ipynb
requirements_python.txt
src/config.py
src/db/clickhouse.py
src/db/neo4j_driver.py
src/label_data_utils.py
src/metrics/activity_openrank.py
src/metrics/attention.py
src/metrics/basic.py
src/metrics/chaoss.py
src/metrics/index.py
src/metrics/related_users.py
src/open_digger.py
src/opendigger.py

I have done the python kernel, but only test some cases using `Clickhouse` mirror. `Neo4j` API haven't been tested ever.

Feat: Add Python kernel

---

labeled_data/communities/xlab/index.yml

data: add x-lab members

---

src/db/clickhouse.py
src/db/neo4j_driver.py
src/metrics/activity_openrank.py
src/metrics/basic.py
src/metrics/index.py
src/metrics/related_users.py
src/open_digger.py

close #962 
Remove `getRepoActivityWithDetail` function and change `getRepoActivity` to use Clickhouse driver and `getRepoOpenrank` only use Neo4j driver.

[metrics] modify index interface of python kernel

---

labeled_data/communities/xlab/index.yml

Add @Best-Eminem into X-lab member

[Data] add x-lab member

---

docs/assets/data_description.csv

fix: update data_description.csv

---

docs/community_meeting_record.yaml

related to https://github.com/X-lab2017/open-wonderland/issues/180

docs: update community_meeting_records.yaml

---

labeled_data/communities/xlab/index.yml

data: Add new member and org to x-lab

---

.github/hypertrons.json

Add new committer to Hypertrons config file.

Add new committer

---

sample_data/start_server.sh

Like #993 , we also need to correct this command.

Correct the command in start_server.sh with the same reason of #993.

---

docs/README.md

docs: fix a broken link in docs/README.md

---

.github/hypertrons.json
labeled_data/regions/China.yml

update chinese developer label and add issue replier message

---

labeled_data/communities/mulan/index.yml

data: change jianmu name

---

labeled_data/technology/database/content.yml
labeled_data/technology/database/document.yml
labeled_data/technology/database/event.yml
labeled_data/technology/database/graph.yml
labeled_data/technology/database/index.yml
labeled_data/technology/database/key_value.yml
labeled_data/technology/database/multivalue.yml
labeled_data/technology/database/native_xml.yml
labeled_data/technology/database/object_oriented.yml
labeled_data/technology/database/rdf.yml
labeled_data/technology/database/relational.yml
labeled_data/technology/database/search_engine.yml
labeled_data/technology/database/spatial.yml
labeled_data/technology/database/time_series.yml
labeled_data/technology/database/wide_column.yml

close #1055 
I test the result in my local env and here are some screenshots:
We got 111 repos in database area and the total OpenRank trending.
OpenRank trending in sub area.
OpenRank trending group by Company

data: add database label data

---

README.md

close #1030 
- Add a user section to replace the development section in README
- Optimize the metrics data URLs with a root URL and relative path which will make it more clear.
- Add a data source badge and encourage users to add the badge to their own projects.

doc: add user section and optimize url

---

CITATION.cff

close #1072 
Add a citation file to OpenDigger so researchers can cite us easily.

doc: add citation file

---

src/cron/tasks/monthly_export.ts

Change date format format from `yyyym(m)` to `yyyy-mm`.
close #1074

refactor: change the date format for export data

---

src/cron/tasks/open_leaderboard.ts

Fix some minor bugs of open leaderboard cron task.

fix: minor fix of leaderboard task

---

src/metrics/chaoss.ts
src/metrics/index.ts
src/open_digger.js

we can discuss the details here.

metric：Issue Response Time

---

labeled_data/companies/alibaba/index.yml
labeled_data/companies/hashicorp/index.yml

close #1095 
Add 3 new orgs into Alibaba
Also fix a typo of HashiCorp

data: Add 3 orgs into alibaba

---

src/cron/tasks/network_export.ts
src/db/neo4j.ts

close #1081 
Add a cron task to export developer network and repo network for users and repos.

feat: export hypercrx network from neo4j

---

src/cron/tasks/monthly_export.ts

close #1040 
In export data process, handle data loss of 2021.10 for statistical metrics for monthly data since GHArchive has a [data service failure](https://github.com/igrigorik/gharchive.org/issues/232#issuecomment-678798777) in 2021.10 for about 2 weeks.
Use 2021.8 - 2021.12 data to estimate 2021.10 data and store the original data to `2021-10-raw` field.

feat: add handle data loss for 2021.10

---

src/cron/tasks/monthly_export.ts

fix #1107 
Add labeled repo and users to export table no matter what the OpenRank value is.

refactor: add label data to export repo and user

---

python/config.py
python/label_data_utils.py
python/metrics/activity_openrank.py
python/metrics/attention.py
python/metrics/basic.py
python/metrics/chaoss.py

In this PR, I changed table name in python kernel.
I test all metrics excludes some about openrank in neo4j and it works well.

feat: update clickhouse schema

---

labeled_data/application_domain/application_software/index.yml
labeled_data/application_domain/libraries_and_frameworks/index.yml
labeled_data/application_domain/non_software/index.yml
labeled_data/application_domain/software_tools/index.yml
labeled_data/application_domain/system_software/index.yml

update application domian data type

fix:change application domian data type

---

src/cron/tasks/monthly_export.ts

fix #1115 
To eliminate the duplicate names from export table, we should not only use names as group key, we should do this in 2 steps:
- Use id as group key to find out the latest names for all ids, this is for rename situation which is more than one name related to a single id.
- Use name as group key to find out the latest id for all names, this is for delete and re-create situation which is more than one id related to a single name.
With these two steps, we can eliminate expired repo names and actor logins to avoid generating wrong data for export task.

fix: duplicate name in export table

---

labeled_data/regions/China.yml
src/metrics/index.ts

close #1121 
And also fix a conflict error in source code.

data: add a new user to china

---

labeled_data/companies/stoneatom/index.yml
labeled_data/companies/stoneatom/stonedb.yml
labeled_data/regions/China.yml
src/label_data_utils.ts

Add StoneAtom and StoneDB label.
close #1124 
Also add `Domain-0` to label type to support new label.

data: add stonedb label

---

README.md

Add Node.js CI badge to readme file.

doc: add ci badge

---

labeled_data/companies/alibaba/index.yml

Add `polardb` org to Alibaba label data.

data: add polardb to alibaba

---

labeled_data/companies/alibaba/index.yml

Add KubeVela org to Alibaba label.

data: add kubevela to alibaba

---

labeled_data/bot/index.yml
src/label_data_utils.ts

1. create `bot` folder and  the template
2. add some bot-label data

feat: add bot-lable data #1089

---

docs/assets/data_description.csv

close #1122 
As we add PullRequestReviewEvent into ClickHouse database, we need to add the schema to the docs as well.

doc: add pull review related columns

---

labeled_data/README.md

update README.md in labeled_data

doc:update readme.md in labeled_data

---

docs/README.md

cc @frank-zsy 
If we have new reports, I'm glad to update the doc contents for them.

Remove unmaintained reports

---

docs/_sidebar.md
docs/metrics/openrank.md
docs/metrics/project_openrank.md

related to #1183 
Add a new website page for project OpenRank index.

doc(website): add index doc for project openrank

---

labeled_data/communities/xlab/index.yml

related to #864 
Add @Miaheeee to X-lab member

data: add new member to xlab

---

.github/workflows/preview.yml

Add a new workflow to deploy preview page on PR that modifies any file under `docs/` folder using [`pr-preview-action`](https://github.com/marketplace/actions/deploy-pr-preview).

ci: add preview workflow

---

labeled_data/foundations/openjs.yml

close #1199 
Add OpenJS Foundation label data from: https://openjsf.org/projects/

data: add openjs label data

---

README.md
docs/README.md

Change table format from Markdown flavor to HTML flavor which makes the table more clear since we can merge some cells with same content.

doc: update table format

---

labeled_data/companies/baidu/index.yml
labeled_data/companies/jd/index.yml
labeled_data/technology/blockchain/index.yml

close #1210 
The label data is from CSDN programmer magazine.

data: add block chain label data

---

labeled_data/companies/espressif/index.yml
labeled_data/companies/fmsoft/index.yml
labeled_data/companies/samsung/index.yml
labeled_data/companies/tencent/index.yml
labeled_data/technology/iot/index.yml

close #1212 
Add IoT label data from CSDN programmer magazine.

data: add iot label data

---

docs/_sidebar.md
docs/file_structure.md
docs/zh-cn/_sidebar.md
docs/zh-cn/file_structure.md

close #508 
Add file structure markdown files to website.

docs(website): add file structure

---

notebook/handbook.ipynb
notebook/handbook_zh.ipynb

fix #1221 
I have fixed these misspellings in the handbooks.

fix: the misspellings in the handbooks

---

src/metrics/basic.ts
src/metrics/indices.ts

Fix a minor bug of activity index.

fix: fix time aggregation for activity

---

docs/zh-cn/README.md

close #1228 This PR synchronizes Chinese README with English README

[Docs] synchronizes chinese version README wht English version

---

labeled_data/companies/alibaba/index.yml
labeled_data/companies/fit2cloud/index.yml

Hi, this PR processed the label data submitted in previous issues.
closed #1232 #1234

update label data add new group to alibaba and fit2cloud

---

labeled_data/technology/ai/generative_ai/index.yml
labeled_data/technology/ai/index.yml

#1249 
update labeled data of Generative AI provided by [the article](https://www.decibel.vc/content/launching-the-generative-ai-open-source-genos-index)

add labeled data: generative ai

---

labeled_data/communities/xlab/index.yml

related to #864 
Add 4 new members to X-lab community

label: add new members to x-lab

---

README.md

docs: fix typo of `user login`

---

src/metrics/basic.ts

fix #1279 
`arrayJoin` function with 2 columns will cause a multiply of different values and result is wrong right now.
Use `arrayJoin... AS ` to fix the error and return corresponding label id and label name.

fix: label group error

---

README.md
docs/README.md
docs/zh-cn/README.md

resolve #1256 
preview: https://github.com/tyn1998/open-digger/blob/eb6ee0f247528175afad3998ff75a5935646259b/README.md
Demo：https://codepen.io/tyn1998/pen/KKGxVrm

docs: add a row of activity_details to the table in README

---

src/cron/tasks/monthly_export.ts

close #1270 
Add `org` and `user` repos meta data to indicate which repos are indexed by OpenDigger.
close #1269 
Add label info into meta data.

feat: add org and user repo meta and label meta

---

python/label_data_utils.py

I added the 'Domain-0' and 'Bot' label in the python kernel.

update the supportedTypes

---

labeled_data/technology/database/index.yml

Fix https://github.com/X-lab2017/open-digger/issues/1315
Add new labels index.yml to complement dbms label data.
Add labels array, hierarchical, network, vector to database index.yml and sort labels alphabetically in ascending order.

Fix: Add labels array, hierarchical, network, vector to database index.yml and sort labels.

---

labeled_data/companies/amazon/index.yml

fix: add bottlerocket to index.yml

---

labeled_data/technology/ai/generative_ai/index.yml

I want to add some labeled data into OpenDigger to help us for our community analysis. The data is based on a dataset fused by data from [GenOs Index](https://www.decibel.vc/articles/genos-index-the-april-aka-the-frenetic-pace-edition).

data:Add more label data for generative artificial intelligence

---

src/cron/tasks/monthly_export.ts

close #1331 
This PR will add an owner type with `user` or `org` in the meta data of each account.
And I need to add `org_id` column in export repo table to find out the repo is from an org or a user.

feat: export owner type in meta data.

---

labeled_data/companies/bytedance/index.yml

close #1338 
Add more orgs into bytedance label data.

label: modify bytedance data

---

python/metrics/activity_openrank.py
python/metrics/basic.py
python/metrics/chaoss.py
python/open_digger.py

In this issuecomment [#148](https://github.com/X-lab2017/open-digger/issues/1265#issuecomment-1646822709), I have covered the main work of this pr. After doing what was mentioned in [#148](https://github.com/X-lab2017/open-digger/issues/1265#issuecomment-1646822709), I refactored all of the existing metric in the python kernel.

refactor: improve python kernel

---

src/cron/tasks/monthly_export.ts

close #1350 
This PR add `id`, `type` to all exported users, repos, orgs meta file.
Also fix duplicate labels in meta file.

feat: unify meta data

---

labeled_data/companies/alibaba/index.yml

label: add orgs to alibaba

---

labeled_data/bot/index.yml

label: add more bot accounts

---

labeled_data/technology/ai/generative_ai/code.yml
labeled_data/technology/ai/generative_ai/image.yml
labeled_data/technology/ai/generative_ai/text.yml

Add code, image and text label data in AI.

label:add code, image and text label data in AI.

---

labeled_data/communities/xlab/index.yml

add new contributors

---

labeled_data/technology/ai/generative_ai/application/index.yml
labeled_data/technology/ai/generative_ai/index.yml
labeled_data/technology/ai/generative_ai/model/index.yml
labeled_data/technology/ai/generative_ai/tool/index.yml
labeled_data/technology/ai/index.yml
labeled_data/technology/ai/large_language_model/index.yml

add LLM and AIGC label data in AI.
LLM label mainly referred to the following：
https://github.com/Hannibal046/Awesome-LLM
AIGC label mainly referred to the following:
https://www.decibel.vc/articles/genos-index-the-june-edition-5-emerging-trends-among-generative-ai-open-source-projects
https://www.decibel.vc/articles/genos-index-the-may-edition-stability-on-the-horizon-maybe
In the article, AIGC projects are divided into tool, model, and application.

data:add llm and aigc label data.

---

labeled_data/companies/alibaba/index.yml

close #1398 
Add new org to alibaba

label: add new org to alibaba

---

docs/assets/data_description.csv

close #1407 
Add repository topics column into ClickHouse schema and all the data has been imported.

doc: add repo topic column

---

src/cron/tasks/monthly_export.ts

close #1408 
Export all the repos and users to `repo_list.csv` and `user_list.csv` for downstream use.

feat: export all repo and user list

---

labeled_data/technology/ai/generative_ai/application/audio.yml
labeled_data/technology/ai/generative_ai/application/code.yml
labeled_data/technology/ai/generative_ai/application/image.yml
labeled_data/technology/ai/generative_ai/application/other.yml
labeled_data/technology/ai/generative_ai/application/text.yml
labeled_data/technology/ai/generative_ai/application/video.yml
labeled_data/technology/ai/generative_ai/infrastructure/data.yml
labeled_data/technology/ai/generative_ai/infrastructure/document.yml
labeled_data/technology/ai/generative_ai/infrastructure/platform_and_environment.yml
labeled_data/technology/ai/generative_ai/infrastructure/vector_database.yml
labeled_data/technology/ai/generative_ai/model/framework_and_architecture.yml
labeled_data/technology/ai/generative_ai/model/fundamental_model.yml
labeled_data/technology/ai/generative_ai/model/variant_model.yml
labeled_data/technology/ai/generative_ai/music.yml
labeled_data/technology/ai/generative_ai/tool/deployment_tool.yml
labeled_data/technology/ai/generative_ai/tool/develop_tool.yml
labeled_data/technology/ai/generative_ai/tool/production_monitor.yml
labeled_data/technology/ai/generative_ai/tool/prompt_engineering.yml

redesign the categories for generative_ai labels and add new labels. 
The new dictionary structure and explanation are as follows:
|--application
|--|--audio : audio applications, including the speech and music applications in the former yml.
|--|--code
|--|--image
|--|--other :  applications in other business domains, such as finance, law, healthcare, meteorology, and so on.
|--|--text
|--|--video
|
|
|--infrastructure
|--|--data  : datasets and related repositories.
|--|--document : including tutorial documents, guides, learning materials, summary documents, and so on.
|--|--platform and environment  :  experiment platform and runtime environment.
|--|--vector database
|
|
|--model
|--|--framework and architecture
|--|--fundamental model  :  fundamental and classical models …

Redesign the categories for generative_ai labels and add new labels

---

labeled_data/communities/xlab/index.yml

this PR adds new xlab member @huangfan0

add new xlab member

---

package-lock.json
package.json
src/cron/tasks/update_github_users.ts

This PR will make the user update cron task to update information for all the users in GitHub log events but not only the exported ones.

feat: update user info for all users in github log

---

src/cron/tasks/update_location.ts

This PR will add longitude and latitude to location update process.

feat: add latitude and longitude to location

---

package-lock.json
package.json
src/config.ts
src/cron/tasks/issue_reaction_importer.ts

This PR adds a cron task to import GitHub reactions for the repos that installed open-digger-bot into gh_events table.
The reactions id will be used as the event log id.

feat: add reaction importer task

---

notebook/openrank_fitting/main.ipynb

This is the code of Opensoda T3 problem:  Openrank fitting and optimization using machine learning.

Openrank fitting and optimization using machine learning

---

labeled_data/companies/huawei/index.yml

Fix the Huawei label data with project label.

fix: add huawei project label

---

src/config.ts
src/cron/index.ts
src/cron/tasks/global_openrank.ts
src/cron/tasks/issue_reaction_importer.ts
src/cron/tasks/monthly_export.ts
src/cron/tasks/network_export.ts
src/cron/tasks/open_leaderboard.ts
src/cron/tasks/remove_rename.ts
src/cron/tasks/update_github_users.ts
src/cron/tasks/update_location.ts

refactor: extract task config to config file

---

src/cron/tasks/update_github_users.ts

- Fix some errors in update GitHub users task.
- Add a priority users table which is used to store users for important customers of OpenDigger.
- Reduce update batch size for 2 tasks which gets users list from events table which is time consuming.

fix: add priority users in update github users

---

labeled_data/foundations/linux_foundation/cncf.yml

Add k8s into CNCF label and change the name to full name.

label: add k8s into cncf

---

labeled_data/companies/kyligence/index.yml
labeled_data/companies/merico/index.yml
labeled_data/companies/oushu/index.yml
labeled_data/companies/sphereex/index.yml

Add some missing orgs for companies label.

label: add missing orgs for companies

---

labeled_data/foundations/linux_foundation/finops.yml
labeled_data/foundations/linux_foundation/hyperledger.yml
labeled_data/foundations/linux_foundation/o3de.yml
labeled_data/foundations/linux_foundation/openssf.yml
labeled_data/foundations/linux_foundation/riscv.yml

Add label for OpenSSF, Hyperledger, FinOps, O3DE, RISCV foundation

label: add OpenSSF, Hyperledger, FinOps, O3DE, RISCV Foundation label data

---

package-lock.json
package.json
src/cron/tasks/community_openrank.ts
src/db/clickhouse.ts

close #1492 
Add community_openrank task, since with 12 concurrent workers and 2GB memory for each worker, change the memory setting to 25.6GB for cron task command.

feat: add community openrank cron task

---

labeled_data/companies/bytedance/index.yml

label: update bytedance

---

src/cron/tasks/community_openrank.ts

close #1499 
Add `repo_name`, `org_id`, `org_login`, `actor_login` into community_openrank table.

feat: add columns into community openrank table

---

src/cron/tasks/community_openrank.ts

Fix bugs about org_id and org_login in community openrank table.

fix: fix community openrank org_id and org_login

---

labeled_data/companies/alibaba/index.yml
labeled_data/companies/alibaba/paimon.yml

close #1501
Add paimon to alibaba label.

label: add paimon

---

src/metrics/indices.ts

Add platform and actor_id in community openrank API, which will help application to know who they are and generate the URL and avatars for the users.

refactor: add platform and actor_id in community openrank

---

labeled_data/bot/index.yml
src/metrics/indices.ts

Fix aggregate functions for community openrank.

fix: fix agg func for community openrank

---

labeled_data/companies/alibaba/arthas.yml
labeled_data/companies/alibaba/canal.yml
labeled_data/companies/alibaba/datax.yml
labeled_data/companies/alibaba/easyexcel.yml
labeled_data/companies/alibaba/havenask.yml
labeled_data/companies/alibaba/higress.yml
labeled_data/companies/alibaba/index.yml
labeled_data/companies/alibaba/polardb-pg.yml
labeled_data/companies/alibaba/polardb-x.yml
labeled_data/companies/alibaba/sca.yml

Add more project labels for alibaba.

label: add more projects for alibaba

---

labeled_data/companies/alibaba/havenask.yml
labeled_data/companies/alibaba/ice.yml
labeled_data/companies/alibaba/polardb-x.yml

fix: fix alibaba project names

---

labeled_data/companies/alibaba/fusion.yml
labeled_data/companies/alibaba/index.yml

label: add fusion as a project

---

labeled_data/companies/alibaba/celeborn.yml
labeled_data/companies/alibaba/index.yml

Add Apache Celeborn to Alibaba label.

label: add celeborn to alibaba

---

src/cron/index.ts
src/cron/tasks/issue_reaction_importer.ts

Fix type error for GitHub app and cron task.

refactor: fix type for github app and cron

---

labeled_data/companies/zilliz/index.yml

label: add zilliztech to Zilliz.

---

labeled_data/companies/greptime/index.yml

Please help review @frank-zsy. Also, I wonder how this label data helps ...
cc @killme2008

Add Greptime company label info

---

labeled_data/companies/siliconflow/index.yml
labeled_data/regions/CN.yml
labeled_data/technology/ai/generative_ai/tool/develop_tool.yml
labeled_data/technology/ai/large_language_model/index.yml

label: add siliconflow

---

src/metrics/indices.ts

Add a `withBot` option to community OpenRank interface, the option is default `true` which means the interface will return contribution of bot accounts.

refactor: add withBot option to community openrank interface

---

labeled_data/companies/alibaba/anolis.yml
labeled_data/companies/deepin/linglong.yml
labeled_data/foundations/openatom/hapjs.yml
labeled_data/foundations/openatom/open_brother.yml
labeled_data/foundations/openatom/openblock.yml
labeled_data/foundations/openatom/rtthread_nano.yml

close #1555 
Fix the names of OpenAtom foundation.

fix: fix names of openatom foundation

---

labeled_data/foundations/linux_foundation/o3d.yml

close #1557 
Fix the name of O3DF

fix: fix name of o3df

---

labeled_data/bot/index.yml
labeled_data/companies/daocloud/index.yml
labeled_data/regions/CN.yml

close #1545 
close #1548 
- Add more GitHub bot account
- Add DaoCloud developers and company label
- Add guqing to Chinese developers

label: add more bot and daocloud

---

package.json
sample_data/README.md

Change self hosted docker hub to aliyun public registry to reduce cost.

refactor: change docker hub to public registry

---

labeled_data/companies/alibaba/seata.yml

Update Seata label since it joined Apache Software Foundation.

label: update seata to apache

---

labeled_data/communities/kaiyuanshe/index.yml
labeled_data/communities/openbuild/index.yml
labeled_data/regions/CN.yml

Add Kaiyuanshe and OpenBuild community label.

label: add openbuild and kaiyuanshe community

---

labeled_data/communities/xlab/index.yml

label: add new xlab members

---

src/cron/tasks/monthly_export.ts

This PR will sort the export repo and user list with OpenRank in desc order.
This will help with some advance search functions.

refactor: add order to export list

---

package-lock.json
package.json
src/cron/tasks/community_openrank.ts
src/cron/tasks/monthly_export.ts
src/utils.ts

close #1497 
This PR will export the community OpenRank while calculate the metrics. The data will be exported to https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/community_openrank.json file.

feat: export commumity openrank to files

---

labeled_data/regions/CN.yml

close #1603 
Add some new Chinese users label data.

label: add chinese users

---

labeled_data/bot/index.yml
labeled_data/regions/CN.yml

close #1608 
Update CN user and bot label.

label: update label for CN and bot

---

labeled_data/bot/index.yml

label: add more robots account

---

labeled_data/regions/CN.yml
src/metrics/basic.ts
src/metrics/indices.ts

- Add user community OpenRank interface, this is the first interface which will both use repo filter and user filter.
- Add yyx to China label.

feat: add user community openrank interface

---

labeled_data/bot/index.yml
src/cron/tasks/community_openrank.ts
src/cron/tasks/global_openrank.ts
src/cron/tasks/monthly_export.ts

Add more bot account along with some minor fixes.

label: add more bot

---

labeled_data/companies/kylin_soft/index.yml
labeled_data/companies/kylin_soft/openkylin.yml
labeled_data/regions/CN.yml

label: add kylin soft and openkylin

---

labeled_data/companies/deepin/codeya_ide.yml
labeled_data/companies/huawei/index.yml
labeled_data/companies/huawei/kurator.yml
labeled_data/companies/huawei/open_inula.yml
labeled_data/foundations/openatom/crowdos.yml
labeled_data/foundations/openatom/hsm.yml
labeled_data/foundations/openatom/index.yml
labeled_data/foundations/openatom/open_solon.yml

Add some new OpenAtom project labels.

label: add more openatom label

---

labeled_data/companies/antgroup/asterinas.yml
labeled_data/companies/antgroup/index.yml

I have updated the labels of opensource projects sponsored by Ant Group

label: update antgroup labels

---

labeled_data/companies/daocloud/index.yml
labeled_data/companies/stackblitz/index.yml
labeled_data/foundations/apache/index.yml
labeled_data/foundations/linux_foundation/cncf/index.yml
labeled_data/foundations/linux_foundation/cncf/tikv.yml
labeled_data/foundations/linux_foundation/zephyr.yml
labeled_data/projects/skywalking.yml
src/data_production/china_annual_report.ts
src/data_production/leaderborads.ts
src/metrics/metrics.ts

Add data production script for china annual report OpenRank ranking list part.

feat: add script for china annual report

---

src/data_production/ospp.ts

feat: add script for ospp analysis

---

src/cron/tasks/update_github_repos.ts

Add a cron task to update GitHub repo info for export repos.

feat: add cron task for update github repos.

---

labeled_data/bot/index.yml
src/dataProduction/communityOpenrankLeaderboards/alibaba_openrank_data.json
src/dataProduction/communityOpenrankLeaderboards/antgroup_openrank_data.json
src/dataProduction/communityOpenrankLeaderboards/communityOpenrankLeaderboards.ts
src/dataProduction/communityOpenrankLeaderboards/meta.json
src/dataProduction/communityOpenrankLeaderboards/xlab_openrank_data.json
src/dataProduction/updateGitHubBotAvatar.ts

close #1689 
Support community openrank leaderboards scripts for OpenDigger website.

feat: add script to generate community openrank leaderboards

---

src/dataProduction/globalDeveloperAnalysis.ts
src/db/clickhouse.ts

Script to generate the data used by the blog: https://open-digger.cn/blog/2025-4-11-global-developer-analysis
Related to https://github.com/X-lab2017/open-wonderland/issues/455

feat: add global developer analysis script

---

src/config.ts
src/cron/tasks/fetchPullDiff.ts
src/cron/tasks/monthlyExport.ts

Add a cron task to fetch pull diff content into database, which is for pull value evaluation for community openrank.

feat: add fetch pull diff task

---

src/cron/tasks/fetchPullDiff.ts
src/cron/tasks/updateGithubUsers.ts

Extract update GitHub users cron tasks config and add a max diff size config to reduce diff store in database.

refactor: update config for cron tasks
